name: Backend CI / CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m venv venv
          venv/bin/pip install --upgrade pip setuptools
          venv/bin/pip install -r requirements.txt
          venv/bin/pip install -r backend/requirements.txt
          venv/bin/pip install -r frontend/requirements.txt
          venv/bin/pip install pylint black pytest pytest-cov

      - name: Run Black Formatter
        run: |
          venv/bin/black --check --diff backend

      - name: Run Pylint
        run: |
          venv/bin/python -m pylint --ignored-modules=pytest --disable=redefined-outer-name backend

      - name: Run tests with coverage
        run: |
          venv/bin/python -m pytest tests
      
      - name: Configure SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "-----BEGIN OPENSSH PRIVATE KEY-----
            ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMu5uDr8e2rY0jV06uJyZ8dToG4gtNFn3OqqwyMWFRRc josephchege@10-17-42-116.dynapool.wireless.nyu.edu
            -----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
        
      - name: Add Hosts
        run: |
            ssh-keyscan -H 68.183.21.82 >> ~/.ssh/known_hosts
        
      - name: Deploy to DigitalOcean
        run: |
            ssh -o StrictHostKeyChecking=no root@68.183.21.82 << 'EOF'
              cd /root/5-final-super-awesome-team-name-2
              git pull origin main
              docker-compose down
              docker-compose up -d --build
            EOF        
