name: Publish Docker Image and Deploy to DigitalOcean

on:
  pull_request:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t lucaignatescu/y2k-final-project:latest .
          docker push lucaignatescu/y2k-final-project:latest

  deploy:
    needs: build-and-push  
    runs-on: ubuntu-latest

    steps:
      - name: Deploy App to DigitalOcean
        uses: appleboy/ssh-action@v1.2.0 
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            set -e

            echo "Navigating to the app directory..."
            cd app

            echo "Pulling the latest changes from the repository..."
            git pull

            echo "Stopping and removing existing Docker services..."
            docker compose down || echo "No services were running, skipping 'docker compose down'."

            echo "Building Docker images..."
            docker compose build

            echo "Starting the services in detached mode..."
            docker compose up -d

            echo "Deployment completed successfully!"
